spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asclepi-core
    username: asclepi_admin
    password: asclepi_admin_password
  jpa:
    hibernate:
      ddl-auto: update

security:
  secret: superSecretSecret
  serverInteger: 1
  admin:
    login: admin
    password: admin
    name: AdminName
    surname: AdminSurname

# todo configure logging
logging:
  level:
    root: DEBUG
