spring:
  # todo normal datasource for production
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:in_memory_test_db
    username: test
    password: test

  jpa:
    open-in-view: false

  h2:
    console:
      enabled: true

security:
  secret: ${ASCLEPI_SECURITY_SECRET}
  serverInteger: ${ASCLEPI_SECURITY_SERVER_INTEGER}
  admin:
    login: ${ASCLEPI_SECURITY_ADMIN_LOGIN}
    password: ${ASCLEPI_SECURITY_ADMIN_PASSWORD}
    name: ${ASCLEPI_SECURITY_ADMIN_NAME}
    surname: ${ASCLEPI_SECURITY_ADMIN_SURNAME}

# todo configure logging
#logging:
#  level:
#    root: debug
