spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:in_memory_test_db
    username: test
    password: test

  jpa:
    open-in-view: false

  h2:
    console:
      enabled: true

# todo through environmental variables
security:
  secret: secret
  serverInteger: 1
  admin:
    login: admin
    password: admin
    name: Admin
    surname: Admin

# todo configure logging
