spring:
  # todo normal datasource for production
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:in_memory_test_db
    username: test
    password: test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

security:
  secret: superSecretSecret
  serverInteger: 1
  admin:
    login: admin
    password: admin
    name: AdminName
    surname: AdminSurname

# todo configure logging
logging:
  level:
    root: debug
